# Generated by Django 5.0.3 on 2024-12-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='instructions_moderator',
            field=models.BooleanField(blank=True, default=False, verbose_name='Модератор инструкций'),
        ),
    ]
