# Generated by Django 5.0.3 on 2024-12-15 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Изображение', max_length=120, verbose_name='Наименование')),
                ('alt', models.CharField(default='Изображение', max_length=120, verbose_name='Альтернативное наименование')),
                ('file', models.FileField(upload_to='instructions/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruction_files_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': ('Файл к инструкции',),
                'verbose_name_plural': ('Файлы к инструкции',),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('visible_listeners', models.JSONField(blank=True, null=True, verbose_name='Настройки видимости у учеников')),
                ('visible_teachers', models.JSONField(blank=True, null=True, verbose_name='Настройки видимости у преподавателей')),
                ('visible_administrators', models.JSONField(blank=True, null=True, verbose_name='Настройки видимости у администраторов')),
                ('visible_methodists', models.JSONField(blank=True, null=True, verbose_name='Настройки видимости у методистов')),
                ('visible_curators', models.JSONField(blank=True, null=True, verbose_name='Настройки видимости у кураторов')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее изменение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruction_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('files', models.ManyToManyField(related_name='instruction_files', to='instructions.instructionfiles', verbose_name='Файлы к инструкции')),
            ],
            options={
                'verbose_name': ('Инструкция',),
                'verbose_name_plural': ('Инструкции',),
                'ordering': ['name'],
            },
        ),
    ]
